# Generated by Django 5.1.6 on 2026-02-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
