"""
Django settings for gimnasio_project project.
Generated by 'django-admin startproject' using Django 5.1.6.
"""

import os
import dj_database_url
from pathlib import Path
from decouple import config

# =============================================================================
# CONFIGURACIÓN BASE
# =============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# SEGURIDAD - CLAVE SECRETA
# =============================================================================
SECRET_KEY = config('SECRET_KEY', default='django-insecure-your-secret-key-here-change-in-production')

# =============================================================================
# MODO DESARROLLO/PRODUCCIÓN
# =============================================================================
DEBUG = config('DEBUG', default=True, cast=bool)

# =============================================================================
# HOSTS PERMITIDOS
# =============================================================================
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.railway.app').split(',')

# =============================================================================
# APLICACIONES INSTALADAS
# =============================================================================
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'whitenoise.runserver_nostatic',
    
    # Local apps
    'gimnasio',
]

# =============================================================================
# MIDDLEWARE
# =============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =============================================================================
# URLS
# =============================================================================
ROOT_URLCONF = 'gimnasio_project.urls'

# =============================================================================
# TEMPLATES
# =============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# =============================================================================
# WSGI
# =============================================================================
WSGI_APPLICATION = 'gimnasio_project.wsgi.application'

# =============================================================================
# BASE DE DATOS
# =============================================================================
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}

# =============================================================================
# VALIDACIÓN DE CONTRASEÑAS
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# INTERNACIONALIZACIÓN
# =============================================================================
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

# =============================================================================
# ARCHIVOS ESTÁTICOS (CSS, JavaScript, Images)
# =============================================================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# =============================================================================
# ARCHIVOS MEDIA (Subidos por usuarios)
# =============================================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# CAMPO POR DEFECTO PARA AUTO_INCREMENT
# =============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CONFIGURACIÓN DE LOGIN
# =============================================================================
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# =============================================================================
# CONFIGURACIÓN DE SEGURIDAD - CRÍTICO PARA HTTPS/HTTP
# =============================================================================
# ESTA SECCIÓN ESTÁ OPTIMIZADA PARA FUNCIONAR EN DESARROLLO (HTTP)
# Y AUTOMÁTICAMENTE SE ACTIVARÁ EN PRODUCCIÓN (HTTPS)

if DEBUG:
    # ========================================================================
    # MODO DESARROLLO - SOLO HTTP (SOLUCIÓN PARA TU PROBLEMA)
    # ========================================================================
    
    # Desactivar redirección HTTPS (¡ESTA ES LA CLAVE!)
    SECURE_SSL_REDIRECT = False
    
    # Cookies NO seguras (funcionan en HTTP)
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    
    # Desactivar HSTS completamente
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # No usar cabeceras de proxy en desarrollo
    SECURE_PROXY_SSL_HEADER = None
    
    # Otras configuraciones de seguridad (no afectan HTTP/HTTPS)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
else:
    # ========================================================================
    # MODO PRODUCCIÓN - HTTPS OBLIGATORIO
    # ========================================================================
    
    # Redirección forzosa a HTTPS
    SECURE_SSL_REDIRECT = True
    
    # Cookies seguras (solo HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS - Forzar HTTPS en el navegador por 1 año
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Configuración para cuando estás detrás de un proxy (como Railway)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Seguridad adicional
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Trusted origins para CSRF
    CSRF_TRUSTED_ORIGINS = [
        'https://' + host for host in ALLOWED_HOSTS 
        if host not in ['localhost', '127.0.0.1']
    ]

# =============================================================================
# CONFIGURACIÓN DE LOGGING
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    'loggers': {
        'gimnasio': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}